services:
  server:
    image: salmaturki/5ds7-devops-salma:latest
    container_name: server-spring
    ports:
      - "8089:8089"
    env_file:
      - app.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8089/tpfoyer/actuator/health" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.38
    restart: always
    container_name: db
    volumes:
      - devops_db_data:/var/lib/mysql
      - ./config.my-cnf:/cfg/config.my-cnf
    env_file:
      - db.env
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u $$MYSQL_USER -p$$MYSQL_PASSWORD ping -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  exporter:
    image: prom/mysqld-exporter
    container_name: exporter
    ports:
      - "9104:9104"
    volumes:
      - ./config.my-cnf:/cfg/config.my-cnf
    command:
      - --config.my-cnf=/cfg/config.my-cnf
    depends_on:
      - db
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

volumes:
  devops_db_data: