services:
  server:
    image: salmaturki/5ds7-devops-salma:latest
    container_name: server-spring
    ports:
      - "8089:8089"
    env_file:
      - app.env
    depends_on:
      - db

  db:
    image: mysql:8.0.38
    restart: always
    container_name: db
    volumes:
      - devops_db_data:/var/lib/mysql
    env_file:
      - db.env
    expose:
      - 3306

  exporter:
    image: prom/mysqld-exporter
    container_name: exporter
    ports:
      - "9104:9104"
    volumes:
      - ./config.my-cnf:/cfg/config.my-cnf
    command:
      - --config.my-cnf=/cfg/config.my-cnf
    depends_on:
      - db

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: always

volumes:
  devops_db_data: